Move the logic which relaces a NoClassDefFoundError by a ClassNotFoundException from loadNonBootstrapClass() to Class.forName(). This means that the NoClassDefFoundError will be propagated if it results from resolving a constant. AcuniaClassLoaderTest has been changed to reflect the new, correct, behaviour.